package com.drapeproof.mobile.fabric

import androidx.compose.ui.graphics.BlendMode
import androidx.compose.ui.graphics.Color

enum class FabricLuster {
    MATTE,
    SUBTLE_SHEEN,
    HIGH_GLOSS,
    DIRECTIONAL_VELVET,
    LEATHER_GRAIN,
}

enum class FabricDrape {
    STRUCTURED,
    RELAXED,
    FLUID,
    HEAVY_PLUSH,
    FEATHERLIGHT,
}

data class FabricMaterial(
    val id: String,
    val name: String,
    val icon: String,
    val description: String,
    val luster: FabricLuster,
    val drape: FabricDrape,
    val breathability: String,
    val weaveType: String,
    val blendMode: BlendMode = BlendMode.Overlay,
    val textureAlpha: Float = 0.92f,
    val aoAlpha: Float = 0.28f,
    val specularStrength: Float = 0.15f,
    val anisotropy: Float = 0.0f,
    val sheen: Float = 0.0f,
)

object FabricCatalog {
    val allFabrics: List<FabricMaterial> = listOf(
        FabricMaterial(
            id = "cotton",
            name = "Organic Cotton",
            icon = "🌿",
            description = "Natural soft matte weave, versatile comfort and breathable drape.",
            luster = FabricLuster.MATTE,
            drape = FabricDrape.STRUCTURED,
            breathability = "Very High",
            weaveType = "Plain Weave",
            blendMode = BlendMode.Softlight,
            textureAlpha = 0.88f,
            aoAlpha = 0.22f,
            specularStrength = 0.08f,
        ),
        FabricMaterial(
            id = "linen",
            name = "Natural Linen",
            icon = "🌾",
            description = "Crisp organic slub texture with relaxed, airy summer drape.",
            luster = FabricLuster.MATTE,
            drape = FabricDrape.RELAXED,
            breathability = "Maximum",
            weaveType = "Slub Weave",
            blendMode = BlendMode.Overlay,
            textureAlpha = 0.95f,
            aoAlpha = 0.32f,
            specularStrength = 0.05f,
        ),
        FabricMaterial(
            id = "silk",
            name = "Mulberry Silk",
            icon = "✨",
            description = "Luminous fluid drape with pearlescent specular sheen.",
            luster = FabricLuster.HIGH_GLOSS,
            drape = FabricDrape.FLUID,
            breathability = "High",
            weaveType = "Satin Weave",
            blendMode = BlendMode.Overlay,
            textureAlpha = 0.82f,
            aoAlpha = 0.20f,
            specularStrength = 0.75f,
            anisotropy = 0.70f,
        ),
        FabricMaterial(
            id = "satin",
            name = "Lustrous Satin",
            icon = "💎",
            description = "Glossy liquid drape with high reflective highlights.",
            luster = FabricLuster.HIGH_GLOSS,
            drape = FabricDrape.FLUID,
            breathability = "Medium",
            weaveType = "High-Luster Filament",
            blendMode = BlendMode.Overlay,
            textureAlpha = 0.78f,
            aoAlpha = 0.18f,
            specularStrength = 0.92f,
            anisotropy = 0.85f,
        ),
        FabricMaterial(
            id = "leather",
            name = "Genuine Leather",
            icon = "🧥",
            description = "Rich tactile grain with architectural drape and sleek edge sheen.",
            luster = FabricLuster.LEATHER_GRAIN,
            drape = FabricDrape.STRUCTURED,
            breathability = "Low",
            weaveType = "Full-Grain Nappa",
            blendMode = BlendMode.Hardlight,
            textureAlpha = 0.98f,
            aoAlpha = 0.35f,
            specularStrength = 0.48f,
        ),
        FabricMaterial(
            id = "tweed",
            name = "Heritage Tweed",
            icon = "🧵",
            description = "Multi-tonal woolen weave with distinguished structured texture.",
            luster = FabricLuster.MATTE,
            drape = FabricDrape.STRUCTURED,
            breathability = "Medium",
            weaveType = "Herringbone Bouclé",
            blendMode = BlendMode.Hardlight,
            textureAlpha = 1.0f,
            aoAlpha = 0.38f,
            specularStrength = 0.10f,
        ),
        FabricMaterial(
            id = "corduroy",
            name = "Plush Corduroy",
            icon = "👖",
            description = "Parallel vertical wales with warm tactile ridges and soft drape.",
            luster = FabricLuster.DIRECTIONAL_VELVET,
            drape = FabricDrape.HEAVY_PLUSH,
            breathability = "Medium",
            weaveType = "8-Wale Ribbed Cut",
            blendMode = BlendMode.Hardlight,
            textureAlpha = 0.98f,
            aoAlpha = 0.40f,
            specularStrength = 0.28f,
            sheen = 0.20f,
        ),
        FabricMaterial(
            id = "cashmere",
            name = "Pure Cashmere",
            icon = "🧣",
            description = "Ultra-fine cloud-soft luxury with gentle thermal drape.",
            luster = FabricLuster.MATTE,
            drape = FabricDrape.RELAXED,
            breathability = "High",
            weaveType = "Fine Spun",
            blendMode = BlendMode.Softlight,
            textureAlpha = 0.85f,
            aoAlpha = 0.24f,
            specularStrength = 0.08f,
        ),
        FabricMaterial(
            id = "wool",
            name = "Merino Wool",
            icon = "🐑",
            description = "Brushed fine-gauge knit with tailored warmth and structure.",
            luster = FabricLuster.SUBTLE_SHEEN,
            drape = FabricDrape.STRUCTURED,
            breathability = "High",
            weaveType = "Worsted Weave",
            blendMode = BlendMode.Overlay,
            textureAlpha = 0.94f,
            aoAlpha = 0.30f,
            specularStrength = 0.12f,
        ),
        FabricMaterial(
            id = "denim",
            name = "Structured Denim",
            icon = "👖",
            description = "Durable diagonal twill weave with firm collar structure.",
            luster = FabricLuster.MATTE,
            drape = FabricDrape.STRUCTURED,
            breathability = "Medium",
            weaveType = "3x1 Twill",
            blendMode = BlendMode.Hardlight,
            textureAlpha = 0.96f,
            aoAlpha = 0.34f,
            specularStrength = 0.12f,
        ),
        FabricMaterial(
            id = "velvet",
            name = "Plush Velvet",
            icon = "👑",
            description = "Deep directional light absorption with rich dimensional sheen.",
            luster = FabricLuster.DIRECTIONAL_VELVET,
            drape = FabricDrape.HEAVY_PLUSH,
            breathability = "Medium",
            weaveType = "Cut Pile",
            blendMode = BlendMode.Overlay,
            textureAlpha = 0.96f,
            aoAlpha = 0.42f,
            specularStrength = 0.06f,
            sheen = 0.88f,
        ),
        FabricMaterial(
            id = "chiffon",
            name = "Sheer Chiffon",
            icon = "🪶",
            description = "Featherlight translucent weave with floating ethereal drape.",
            luster = FabricLuster.SUBTLE_SHEEN,
            drape = FabricDrape.FEATHERLIGHT,
            breathability = "Maximum",
            weaveType = "Crepe Twist Plain",
            blendMode = BlendMode.Screen,
            textureAlpha = 0.70f,
            aoAlpha = 0.15f,
            specularStrength = 0.32f,
        ),
        FabricMaterial(
            id = "knit",
            name = "Ribbed Knit",
            icon = "🧶",
            description = "Dimensional textured rib with body-contouring relaxed drape.",
            luster = FabricLuster.MATTE,
            drape = FabricDrape.RELAXED,
            breathability = "High",
            weaveType = "2x2 Rib Knit",
            blendMode = BlendMode.Hardlight,
            textureAlpha = 0.96f,
            aoAlpha = 0.36f,
            specularStrength = 0.14f,
        ),
        FabricMaterial(
            id = "polyester",
            name = "Tech Polyester",
            icon = "🏃",
            description = "Performance moisture-wicking weave with wrinkle-free drape.",
            luster = FabricLuster.SUBTLE_SHEEN,
            drape = FabricDrape.STRUCTURED,
            breathability = "High",
            weaveType = "Micro-Piqué",
            blendMode = BlendMode.Overlay,
            textureAlpha = 0.90f,
            aoAlpha = 0.25f,
            specularStrength = 0.30f,
        ),
    )

    val defaultFabric: FabricMaterial = allFabrics[0]

    fun findById(id: String): FabricMaterial {
        return allFabrics.firstOrNull { it.id.equals(id, ignoreCase = true) } ?: defaultFabric
    }
}
